# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: angis-go
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angis-go
  template:
    metadata:
      labels:
        app: angis-go
    spec:
      containers:
      - name: angis-go
        image: 895879716483.dkr.ecr.us-west-2.amazonaws.com/angis-go:65
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: angis-app-service
  namespace: app
spec:
  selector:
    app: angis-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
